variables:

  # Global
  ap_vm_image: windows-2019

  location: eastus 
  prefix: fasthack 
  postfix: uc2
  environment: dev
  objectID: 'bfb89611-c0c4-4d47-a934-dcd6a960b148'

  # Azure DevOps 
  ado_service_connection_rg: Azure-ARM-Dev-SAPA
  # github
  gihub_repo_name: "Azure/fasthackonsynapse" #Not required if you are not using workspace_publish branch for Azure synapse

  # IaC
  baseName: $(prefix)$(postfix)$(environment)
  resourceGroupName: AP4-$(baseName)-RG
  storageAccountName: $(prefix)st$(postfix)$(env)
  dataLakeAccountName: $(prefix)adl$(postfix)$(env)
  sqlServerName: $(prefix)sql$(postfix)$(env)
  databaseName: sampledb
  synapseWorkspace: $(prefix)-synapse-$(postfix)-$(env)
  synapsedatalakegen2name: $(prefix)adlssyn$(postfix)$(env)
  keyVaultName: $(prefix)-akv-$(postfix)-$(env)


